/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: gelmi.com.br (https://sketchfab.com/rodrigogelmi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/beer-bottle-c3de7f8b092e4092aef14d4ffc9fac7f
Title: Beer Bottle
*/

import { enforceMeshNode } from '@/TypeUtils';
import { useGLTF } from '@react-three/drei';
import { ComponentPropsWithRef } from 'react';

const GLB_PATH = '/3d_models/beer_bottle/scene.glb';

export default function BeerBottle3DModel(props: ComponentPropsWithRef<'group'>) {
  const { nodes, materials } = useGLTF(GLB_PATH);
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={enforceMeshNode(nodes.GARRAFA_VIDRO_FORA_0).geometry}
        material={materials.VIDRO_FORA}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={enforceMeshNode(nodes.GARRAFA_VIDRO_DENTRO_0).geometry}
        material={materials.VIDRO_DENTRO}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={enforceMeshNode(nodes.GARRAFA_LIQUIDO_0).geometry}
        material={materials.LIQUIDO}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={enforceMeshNode(nodes.GARRAFA_TAMPA_0).geometry}
        material={materials.TAMPA}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={enforceMeshNode(nodes.GARRAFA_LIMITE_LIQUIDO_0).geometry}
        material={materials.LIMITE_LIQUIDO}
      />
    </group>
  );
}

useGLTF.preload(GLB_PATH);
