/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sousinho (https://sketchfab.com/sousinho)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/shampoo-bottle-38508e5df44840ebae254e40e1ebd73f
Title: Shampoo bottle
*/

import { enforceMeshNode } from '@/TypeUtils';
import { useGLTF } from '@react-three/drei';
import { ComponentPropsWithRef } from 'react';

const GLB_PATH = '/3DModels/shampooBottle/scene.glb';

export default function ShampooBottle3DModel(props: ComponentPropsWithRef<'group'>) {
  const { nodes, materials } = useGLTF(GLB_PATH);
  return (
    <group
      {...props}
      dispose={null}
    >
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={enforceMeshNode(nodes.SM_Shampoo_bottle_T_Shampoo_bottle_0).geometry}
          material={materials.T_Shampoo_bottle}
          rotation={[-Math.PI / 2, 0, +Math.PI / 2]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload(GLB_PATH);
